# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "125e1e90b66977c91b3f17bb6deb65ff"
name = "rapso-app"
application_url = "https://metadata-cd-butter-pensions.trycloudflare.com"
embedded = true
handle = "rapso-app"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://ia-become-bulgarian-et.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://ia-become-bulgarian-et.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = ["https://metadata-cd-butter-pensions.trycloudflare.com/auth/callback", "https://metadata-cd-butter-pensions.trycloudflare.com/auth/shopify/callback", "https://metadata-cd-butter-pensions.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://metadata-cd-butter-pensions.trycloudflare.com"
subpath = "rapso"
prefix = "apps"

[pos]
embedded = false
